import type { AppState, Deliverable, RiskIssue, ScopeItem, Task } from "./types";
import { defaultTaskStages } from "./services/contextBuilder";

const now = () => new Date().toISOString();

const shiftDate = (dateKey: string, days: number) => {
  if (!dateKey) return "";
  const date = new Date(`${dateKey}T00:00:00`);
  if (Number.isNaN(date.getTime())) return dateKey;
  date.setDate(date.getDate() + days);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
};

const task = (
  id: string,
  projectId: string,
  code: string,
  title: string,
  type: string,
  status: Task["status"],
  stage: Task["stage"],
  dimension: string,
  priority: Task["priority"],
  owner: string,
  dueDate: string,
  progress: number,
  parentId = "",
  startDate = shiftDate(dueDate, parentId ? -2 : -5),
): Task => ({
  id,
  projectId,
  parentId,
  code,
  title,
  type,
  status,
  stage,
  dimension,
  priority,
  owner,
  startDate,
  dueDate,
  progress,
  updatedAt: now(),
});

const scope = (
  id: string,
  projectId: string,
  category: ScopeItem["category"],
  personDayType: ScopeItem["personDayType"],
  title: string,
  description: string,
  estimatedPersonDays: number,
  actualPersonDays: number,
  progress: number,
): ScopeItem => ({
  id,
  projectId,
  category,
  personDayType,
  title,
  description,
  estimatedPersonDays,
  actualPersonDays,
  progress,
  content: title,
});

const deliverable = (id: string, projectId: string, name: string, code: string, status: string, acceptance: string, dueDate: string): Deliverable => ({
  id,
  projectId,
  name,
  code,
  status,
  acceptance,
  dueDate,
  attachmentRequirement: "required",
});

const risk = (
  id: string,
  projectId: string,
  kind: RiskIssue["kind"],
  title: string,
  severity: RiskIssue["severity"],
  status: RiskIssue["status"],
  responsePlan: string,
  linkedTaskId: string,
  riskVisibility: RiskIssue["riskVisibility"] = "internal",
  internalHandling = responsePlan,
  customerAssistance = "",
): RiskIssue => ({ id, projectId, kind, title, severity, status, riskVisibility, responsePlan, internalHandling, customerAssistance, linkedTaskId });

export const defaultData: AppState = {
  schemaVersion: 18,
  ui: {
    currentPage: "portal",
    currentProjectId: "p-crm",
    search: "",
    assistantScope: "project",
  },
  taskStages: defaultTaskStages,
  projectStageConfigs: [],
  projects: [
    {
      id: "p-crm",
      name: "华东CRM实施",
      client: "上海华联集团",
      phase: "数据接入与部署",
      health: "健康",
      owner: "我",
      startDate: "2026-05-10",
      endDate: "2026-07-18",
      progress: 62,
      nextMilestone: "06-07 客户UAT启动",
      description: "覆盖客户资料、销售机会、合同台账和服务工单的CRM实施项目。",
      estimatedImplementationPersonDays: 96,
      estimatedDevelopmentPersonDays: 34,
    },
    {
      id: "p-fin",
      name: "财务共享平台上线",
      client: "远森制造",
      phase: "需求调研",
      health: "关注",
      owner: "我",
      startDate: "2026-05-20",
      endDate: "2026-08-01",
      progress: 38,
      nextMilestone: "06-05 蓝图确认",
      description: "财务共享中心平台蓝图、配置、迁移和上线项目。",
      estimatedImplementationPersonDays: 82,
      estimatedDevelopmentPersonDays: 48,
    },
    {
      id: "p-pos",
      name: "门店POS系统推广",
      client: "新零售事业部",
      phase: "上线试运行",
      health: "延期",
      owner: "我",
      startDate: "2026-04-15",
      endDate: "2026-06-30",
      progress: 76,
      nextMilestone: "06-03 第三批门店上线",
      description: "门店POS分批上线推广，含培训、门店切换和验收。",
      estimatedImplementationPersonDays: 120,
      estimatedDevelopmentPersonDays: 20,
    },
    {
      id: "p-hr",
      name: "HR系统二期部署",
      client: "北方能源",
      phase: "数据接入与部署",
      health: "健康",
      owner: "我",
      startDate: "2026-05-12",
      endDate: "2026-07-02",
      progress: 54,
      nextMilestone: "06-10 数据迁移演练",
      description: "HR系统二期组织、人事、薪酬模块部署。",
      estimatedImplementationPersonDays: 74,
      estimatedDevelopmentPersonDays: 28,
    },
  ],
  tasks: [
    task("t-main-blueprint", "p-crm", "WBS-01", "蓝图与范围确认", "主任务", "customer", "requirements", "WBS", "高", "我", "2026-06-06", 0),
    task("t-main-config", "p-crm", "WBS-02", "配置实施与数据准备", "主任务", "blocked", "deployment", "WBS", "高", "我", "2026-06-07", 0),
    task("t-main-uat", "p-crm", "WBS-03", "UAT与培训准备", "主任务", "doing", "training", "WBS", "中", "我", "2026-06-08", 0),
    task("t-118", "p-crm", "IMP-118", "客户主数据清洗与导入演练", "实施", "doing", "deployment", "数据质量", "高", "顾问", "2026-06-05", 55, "t-main-config"),
    task("t-126", "p-crm", "IMP-126", "配置门店价格策略与审批流", "实施", "doing", "rules", "系统配置", "中", "我", "2026-06-06", 48, "t-main-config"),
    task("t-031", "p-crm", "ISS-031", "UAT环境账号无法登录", "问题", "doing", "training", "问题处理", "高", "运维", "2026-06-03", 35, "t-main-uat"),
    task("t-142", "p-crm", "IMP-142", "准备UAT测试用户与权限矩阵", "实施", "todo", "training", "资源准备", "中", "我", "2026-06-07", 20, "t-main-uat"),
    task("t-151", "p-crm", "IMP-151", "整理第一批培训签到模板", "实施", "todo", "training", "培训", "低", "顾问", "2026-06-08", 0, "t-main-uat"),
    task("t-009", "p-crm", "CR-009", "新增区域经理审批节点", "变更", "customer", "requirements", "客户确认", "高", "客户", "2026-06-04", 25, "t-main-blueprint"),
    task("t-044", "p-crm", "DOC-044", "蓝图确认纪要签字页", "交付物", "customer", "requirements", "交付物", "中", "客户", "2026-06-06", 75, "t-main-blueprint"),
    task("t-017", "p-crm", "RISK-017", "客户主数据质量不足", "风险", "blocked", "deployment", "风险问题", "高", "我", "2026-06-05", 40, "t-main-config"),
    task("t-036", "p-crm", "ISS-036", "蓝图确认纪要签字页缺失", "问题", "blocked", "requirements", "客户确认", "中", "客户", "2026-06-06", 50, "t-main-blueprint"),
    task("t-097", "p-crm", "IMP-097", "完成项目启动会与角色确认", "实施", "done", "kickoff", "客户确认", "低", "我", "2026-05-14", 100),
    task("t-103", "p-crm", "IMP-103", "完成系统初始化参数配置", "实施", "done", "rules", "系统配置", "中", "顾问", "2026-05-30", 100, "t-main-config"),
    task("t-fin-1", "p-fin", "FIN-021", "完成蓝图确认会纪要", "交付物", "customer", "requirements", "客户确认", "中", "客户", "2026-06-05", 65),
    task("t-pos-1", "p-pos", "POS-088", "重排第三批门店上线窗口", "问题", "blocked", "pilot", "里程碑", "高", "我", "2026-06-03", 45),
    task("t-hr-1", "p-hr", "HR-033", "员工主数据迁移演练", "实施", "doing", "deployment", "数据质量", "中", "顾问", "2026-06-10", 54),
  ],
  scopeItems: [
    scope("s-1", "p-crm", "本期SOW范围", "实施", "CRM核心业务对象实施", "客户资料、销售机会、合同台账、服务工单配置与数据初始化。", 52, 31, 62),
    scope("s-2", "p-crm", "本期SOW范围", "实施", "数据迁移与UAT支持", "主数据清洗导入、UAT测试准备、关键用户培训与验收支持。", 44, 27, 58),
    scope("s-3", "p-crm", "变更增加范围", "开发", "区域经理审批节点", "新增区域经理审批节点和历史客户导入字段。", 16, 6, 38),
    scope("s-4", "p-crm", "不在本期范围", "实施", "营销自动化深度集成", "营销自动化、外部呼叫中心深度集成暂不纳入本期。", 0, 0, 0),
  ],
  deliverables: [
    deliverable("d-1", "p-crm", "蓝图确认书-v2.docx", "DOC-044", "待客户签字", "客户验收", "2026-06-06"),
    deliverable("d-2", "p-crm", "主数据导入模板.xlsx", "IMP-118", "已更新", "内部确认", "2026-06-05"),
    deliverable("d-3", "p-crm", "UAT测试用例清单.xlsx", "IMP-142", "草稿", "待评审", "2026-06-07"),
    deliverable("d-4", "p-crm", "关键用户培训PPT.pptx", "TRN-006", "待评审", "客户确认", "2026-06-08"),
    deliverable("d-5", "p-crm", "上线切换方案.pdf", "GO-003", "待补充", "未提交", "2026-06-14"),
  ],
  risksIssues: [
    risk("r-17", "p-crm", "risk", "客户主数据质量不足影响迁移演练", "高", "open", "分批清洗、先导入核心字段、每日校验", "t-118", "external", "项目组整理数据校验规则并每日回传差异清单", "请客户业务负责人补齐主数据缺失字段并确认清洗口径"),
    risk("r-21", "p-crm", "risk", "客户关键用户无法按时参加培训", "中", "tracking", "提前锁定候补用户并调整培训窗口", "t-151", "external", "项目组准备录屏和补训安排", "请客户确认关键用户或候补用户名单"),
    risk("i-31", "p-crm", "issue", "UAT环境账号无法登录", "高", "open", "运维排查SSO配置并补发账号", "t-031", "internal", "运维排查SSO配置并补发账号"),
    risk("i-36", "p-crm", "issue", "蓝图确认纪要签字页缺失", "中", "tracking", "跟进客户项目负责人回签", "t-044", "internal", "项目经理跟进回签材料并完成归档"),
  ],
  aiModelConfigs: [
    {
      id: "ai-gpt55-proxy",
      name: "GPT-5.5 国内代理",
      provider: "openai-compatible",
      baseUrl: "https://api.aicodemirror.com/api/codex/v1/chat/completions",
      model: "gpt-5.5",
      apiKey: "",
      temperature: 0.2,
      isDefault: true,
      allowRemoteRequest: false,
      lastHealth: "待配置代理 Base URL 与 API Key",
    },
    {
      id: "ai-xiaomi-mimo",
      name: "小米 Mimo",
      provider: "openai-compatible",
      baseUrl: "https://token-plan-cn.xiaomimimo.com/v1",
      model: "mimo-v2.5-pro",
      apiKey: "",
      temperature: 0.2,
      isDefault: false,
      allowRemoteRequest: false,
      lastHealth: "待填写 API Key 并测试",
    },
    {
      id: "ai-kimi-k26",
      name: "Kimi K2.6",
      provider: "openai-compatible",
      baseUrl: "https://api.moonshot.cn/v1",
      model: "kimi-k2.6",
      apiKey: "",
      temperature: 1,
      isDefault: false,
      allowRemoteRequest: false,
      lastHealth: "待填写 API Key 并测试",
    },
  ],
  aiMessages: [
    {
      id: "m-1",
      role: "assistant",
      content: "我可以基于当前项目快照回答问题、解释健康评分、生成周报草稿，也可以按明确指令直接更新任务状态、日期、进度和负责人。",
      createdAt: now(),
      scope: "project",
      projectId: "p-crm",
    },
  ],
  aiScores: [],
  weeklyReports: [],
  weeklyReportPreferences: [],
  emailConfig: {
    provider: "tencent-exmail",
    senderName: "",
    email: "",
    username: "",
    password: "",
    smtpHost: "smtp.exmail.qq.com",
    smtpPort: 465,
    smtpSecure: true,
    imapHost: "imap.exmail.qq.com",
    imapPort: 993,
    imapSecure: true,
    draftsMailbox: "Drafts",
    lastStatus: "待配置企业邮箱账号与客户端专用密码",
    updatedAt: "",
  },
  deliveryWorkflows: [],
};
